var a = 10;
var b = 20;
console.log("\uD83D\uDFE2 Arithmatic \uD83D\uDFE2");
console.log("Addition ".concat(a + b));
console.log("Subtraction ".concat(a - b));
console.log("Multiplication ".concat(a * b));
console.log("Division ".concat(a / b));
console.log("Modulus ".concat(a % b));
console.log("Increment ".concat(a++));
console.log(a);
console.log("Decrement ".concat(--a));
console.log(a);
console.log("\uD83D\uDFE2 Assigment \uD83D\uDFE2");
a = 90;
console.log("Assignment ".concat(a));
console.log("Add and Assign ".concat(a += 10));
console.log("Sub and Assign ".concat(a -= 10));
console.log("Mult and Assign ".concat(a *= 10));
console.log("Div and Assign ".concat(a /= 10));
console.log("Div and Assign ".concat(a %= 2));
console.log("\uD83D\uDFE2 Comparision \uD83D\uDFE2");
console.log("Equality ".concat(a == b));
console.log("Strict Equality ".concat(a === b));
var aa = '10';
var bb = 10;
console.log("Normal Equality ".concat(aa == bb));
console.log("Strict Equality ".concat(aa === bb));
console.log("Not Eqauls ".concat(a != b));
console.log("Strict Not Equals ".concat(a !== b));
console.log("GT ".concat(a > b));
console.log("GTE ".concat(a >= b));
console.log("LT ".concat(a < b));
console.log("LTE ".concat(a <= b));
console.log("\uD83D\uDFE2 Logical \uD83D\uDFE2");
console.log("Logical And ".concat((a <= b) && (a == 10)));
console.log("Logical And ".concat((a <= b) || (a == 10)));
console.log("Logical And ".concat(!((a <= b) || (a == 10))));
console.log("\uD83D\uDFE2 Bitwise \uD83D\uDFE2");
console.log(" And ".concat((1 & 7)));
console.log(" Or ".concat((10 | 20)));
console.log(" xor ".concat((2 ^ 5)));
console.log(" Right Shift ".concat((9 >> 1)));
console.log(" Left Shift ".concat((9 << 1)));
console.log("NOT ".concat(~1));
