var em1 = 'aa@dd.com';
var em2 = 'aa@dd';
var em3 = 'aa@dd@ff';
var rg1 = /hello/;
var msg1 = "The quick is red";
var rg2 = /quick/;
console.log(rg2.test(msg1));
var msg2 = "abc";
var rg3 = /\d+/;
console.log(rg3.test(msg2));
